// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_y8S_WFkgOnKS3eJpWkGWdG9G-PyQLWE',
    appId: '1:899248237248:web:dd03850e7cd2b2d7901b25',
    messagingSenderId: '899248237248',
    projectId: 'medinest-4242d',
    authDomain: 'medinest-4242d.firebaseapp.com',
    storageBucket: 'medinest-4242d.firebasestorage.app',
    measurementId: 'G-1R8EBQCBB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUbPJvlY1efy083C54XWTvwTu3EHPvHc',
    appId: '1:899248237248:android:02dd0b69e7833466901b25',
    messagingSenderId: '899248237248',
    projectId: 'medinest-4242d',
    storageBucket: 'medinest-4242d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPzAiAhVVUvMcMhRbuUmgccWwlay1ZtQ',
    appId: '1:899248237248:ios:bd3fa3b88eda227b901b25',
    messagingSenderId: '899248237248',
    projectId: 'medinest-4242d',
    storageBucket: 'medinest-4242d.firebasestorage.app',
    iosBundleId: 'com.example.mymedbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPPzAiAhVVUvMcMhRbuUmgccWwlay1ZtQ',
    appId: '1:899248237248:ios:bd3fa3b88eda227b901b25',
    messagingSenderId: '899248237248',
    projectId: 'medinest-4242d',
    storageBucket: 'medinest-4242d.firebasestorage.app',
    iosBundleId: 'com.example.mymedbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_y8S_WFkgOnKS3eJpWkGWdG9G-PyQLWE',
    appId: '1:899248237248:web:b610efc9acb1b19b901b25',
    messagingSenderId: '899248237248',
    projectId: 'medinest-4242d',
    authDomain: 'medinest-4242d.firebaseapp.com',
    storageBucket: 'medinest-4242d.firebasestorage.app',
    measurementId: 'G-YXB6FFRCRW',
  );
}
